### ISSUE TITLE
Should I set CLOUDFLARE_ACCOUNT_ID? What is SECRET_DISCORD_WEBHOOK_URL?

### ISSUE THREAD

**Issue by nanqic** [yunsii/cf-worker-status-page-pro#3]
Deploy got error:
```
Run cloudflare/wrangler-action@v3
📥 Installing Wrangler
🔑 Uploading secrets...
Error: Failed to upload secrets.
Error: 🚨 Action failed
```
How to deploy it correctly?

And this [commit](https://github.com/yunsii/cf-worker-status-page-pro/commit/39bcd9356a390c55d46c1cdb0999608d2812eba6) added SECRET_DISCORD_WEBHOOK_URL, how to use it?

**Comment by yunsii** [comment]
CLOUDFLARE_API_TOKEN is the only one required env variable, refer to https://github.com/yunsii/cf-worker-status-page-pro#getting-started It will be used by https://github.com/cloudflare/wrangler-action#authentication

As for https://github.com/yunsii/cf-worker-status-page-pro/commit/39bcd9356a390c55d46c1cdb0999608d2812eba6 It will post message to a Discord chat. If you do not need it, you can revert this change.

**Comment by nanqic** [comment]
I follow the instructions, and clicked the [button](https://deploy.workers.cloudflare.com/?url=%5Bhttps://github.com/eidam/cf-workers-status-page%5D(https://github.com/yunsii/cf-worker-status-page-pro), but got same err `Failed to upload secrets.`, is it my fault?

**Comment by yunsii** [comment]
This repo do not supported deploy by https://deploy.workers.cloudflare.com/?url=https://github.com/yunsii/cf-worker-status-page-pro for now.

You should go to https://dash.cloudflare.com/profile/api-tokens and create token with `Edit Cloudflare Workers` template. and follow the [step 2](https://github.com/yunsii/cf-worker-status-page-pro#getting-started) to config github repository secrets with `CLOUDFLARE_API_TOKEN` name.
